# Generated by Django 5.2.14 on 2026-06-08 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0002_access_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='userprofile_role_idx'),
        ),
        migrations.AddIndex(
            model_name='visibilitygrant',
            index=models.Index(fields=['bucket', 'prefix', 'target_type', 'role', 'user', 'group'], name='grant_admin_order_idx'),
        ),
        migrations.AddIndex(
            model_name='visibilitygrant',
            index=models.Index(fields=['bucket', 'access', 'prefix'], name='grant_bucket_access_idx'),
        ),
        migrations.AddIndex(
            model_name='visibilitygrant',
            index=models.Index(fields=['target_type', 'access', 'bucket'], name='grant_target_access_idx'),
        ),
    ]
